### ISSUE TITLE
Cannot find contig definations in represented genomes

### ISSUE THREAD

**Issue by shubavarshini** [AlessioMilanese/progenomes_classifier#1]
I downloaded the fasta file of all the represented genomes in your study (link: http://progenomes.embl.de/data/repGenomes/freeze12.contigs.representatives.fasta.gz). But I cannot find the definitions of these contigs chosen from specI species clustering. I mean taxonomic definition. Could you please help me with the same.

**Comment by pangenomics** [comment]
Hi shubavarshini,
The NCBI taxonomy IDs are included in the fasta headers [format: taxid.projectID.sequenceID]
Does that help?
Best wishes

**Comment by shubavarshini** [comment]
Yes that helps. I used a different tool called taxonkit to extract the lineage of the taxid. Thank you.
