### ISSUE TITLE
Extract protein fasta 

### ISSUE THREAD

**Issue by sodosopah** [AlessioMilanese/progenomes_classifier#3]
Hey!

Is there a way to output protein fasta files of the marker genes instead of (or as well as) the nucleotide fasta?

Thanks!

**Comment by AlessioMilanese** [comment]
Hi @sodosopah 

FetchMG should be able to do that:
https://github.com/motu-tool/fetchMGs

Cheers,
alessio

**Comment by sodosopah** [comment]
Too easy, thanks!
And thanks for a great tool as well!
Cheers
